### ISSUE TITLE
Init script failed

### ISSUE THREAD

**Issue by MarcoFaul** [shopwareLabs/shopware-docker#42] opened 2019-07-17 05:05 UTC
Steps down:
Built docker containers
ssh into docker
called ./psh.phar init script
Step 2 Failed:

`(2/2) Starting
> ./sw.phar install:release -r latest -i ./shopware --db-host mysql --db-user app --db-password app --db-name shopware --shop-host localhost:8083
	
	                                                              
	  [RuntimeException]                                          
	  Could not find / create //.local/share/sw-cli-tools/assets  
	                                                              

Execution aborted, a subcommand failed!`

Thanks in advance!

**Comment by teiling88** [comment] 2019-07-18 06:03
![image](https://user-images.githubusercontent.com/4624237/61432923-35f1aa80-a932-11e9-991f-8e901004ccb6.png)
It works on my machine. I think you have a previous error which is leading in this issue. 
Can you please post the complete output from ./psh.phar docker:start ./psh.phar docker:ssh and ./psh.phar init ?

**Comment by MarcoFaul** [comment] 2019-07-18 06:19
docker:start
![image](https://user-images.githubusercontent.com/6201946/61433746-6a666600-a934-11e9-96d3-8d320813940a.png)

docker:ssh
![image](https://user-images.githubusercontent.com/6201946/61433778-7eaa6300-a934-11e9-9efc-ed6f5cfbdf24.png)

psh.phar init
![image](https://user-images.githubusercontent.com/6201946/61433856-b2858880-a934-11e9-9c3b-523b9badb660.png)

**Comment by teiling88** [comment] 2019-07-18 07:02
In my docker container the directory path ~/.local/share/sw-cli-tools/assets/ exists. Can you please check that on your system?

**Comment by MarcoFaul** [comment] 2019-07-18 14:33
I newly rebuilt my containers and there is no such directory
`~/.local`

**Comment by teiling88** [comment] 2019-07-19 06:32
It exists in my container which I rebuild completely. 

What kind of OS and docker version are you using?

**Comment by MarcoFaul** [comment] 2019-07-19 07:06
first thank you for your help.

MacOS Mojave (10.14.5) and Latest - Docker 2.0.0.3

**Comment by teiling88** [comment] 2019-07-19 07:33
Is it possible for you to create this directories? I never tested this docker setup with MacOs.

**Comment by MarcoFaul** [comment] 2019-07-19 08:59
I tried that before. Permissions denied even with admin rights.

**Comment by shopfreelancer** [comment] 2019-08-05 08:27
The problem is basically caused by the fact Docker and MacOs host try to access the same files and folders. And the Docker user has not sufficient rights to mkdir, hence the RuntimeError. The setup of the whole installation is quite complex so it took me a while but I was able to successfully run the installation by simply executing the sw.phar as root in the docker container. 

This being said: instead of `./psh.phar docker:ssh`use `docker exec -it shopware-docker_app_server_1 bash` to log into your shopware container as root and the installation should work.

**Comment by colinmurphy** [comment] 2019-08-29 06:53
Thanks @shopfreelancer 👍 

I can confirm I had the same issue on Mac and your solution worked for me :) 
I am running MacOS Mojave 10.14.5 with Docker version 2.1.0.1

**Comment by teiling88** [comment] 2019-08-29 07:02
Thanks for your feedback. Therefore I will close this issue!

**Closed by teiling88** 2019-08-29 07:02 UTC
